import React from "react";
import "./App.css";
import PathfindingVisualizer from "./Components/PathfindingVisualizer";

function App() {
  // store everything  other files, as to not break any of the autogenerated files
  return (
    <div className="App">
      <PathfindingVisualizer></PathfindingVisualizer>
    </div>
  );
}

export default App;
